"use client";

import { useState } from "react";
import { Search } from "lucide-react";
import { daysExceededTxnRows, receiverSearchByOptions } from "@/data/securityData";

const columns = [
  "SNO",
  "Dest. Country",
  "District",
  "Receiving Branch",
  "Receiver",
  "Date",
  "Payment Type",
  "Payout Amount",
  "Generated By",
];

export default function DaysExceededTxnPanel() {
  const [receiverName, setReceiverName] = useState("");
  const [searchBy, setSearchBy] = useState(receiverSearchByOptions[0]);
  const [rows, setRows] = useState(daysExceededTxnRows);
  const [searchedAt, setSearchedAt] = useState(() => new Date());

  function handleSearch() {
    setSearchedAt(new Date());
    setRows(
      daysExceededTxnRows.filter((row) =>
        receiverName ? row.receiver.toLowerCase().includes(receiverName.toLowerCase()) : true
      )
    );
  }

  const subTotal = rows.reduce((sum, row) => sum + Number(row.payoutAmount.replace(/,/g, "")), 0);

  return (
    <div className="overflow-hidden rounded-2xl border border-border shadow-card">
      <div className="border-b border-border px-6 py-4">
        <h1 className="text-lg font-bold text-heading">Days Exceeded TXN Requests</h1>
      </div>

      <div className="bg-panel p-6 sm:p-8">
        <div className="rounded-xl border border-border bg-panel p-4">
          <div className="flex flex-col gap-3 sm:flex-row sm:items-end">
            <div className="flex-1">
              <label className="mb-1.5 block text-sm text-heading/70">Receiver Name</label>
              <input
                value={receiverName}
                onChange={(event) => setReceiverName(event.target.value)}
                className="w-full rounded-lg border border-border bg-panel px-3 py-2.5 text-sm text-heading focus:border-brand-green focus:outline-none focus:ring-1 focus:ring-brand-green"
              />
            </div>
            <div className="flex-1">
              <label className="mb-1.5 block text-sm text-heading/70">Search By</label>
              <select
                value={searchBy}
                onChange={(event) => setSearchBy(event.target.value)}
                className="w-full appearance-none rounded-lg border border-border bg-panel px-3 py-2.5 text-sm text-heading focus:border-brand-green focus:outline-none focus:ring-1 focus:ring-brand-green"
              >
                {receiverSearchByOptions.map((option) => (
                  <option key={option} value={option}>
                    {option}
                  </option>
                ))}
              </select>
            </div>
            <button
              onClick={handleSearch}
              className="flex items-center justify-center gap-2 rounded-lg bg-brand-green px-6 py-2.5 text-sm font-semibold text-white shadow-card transition-shadow hover:bg-brand-green-dark hover:shadow-card-hover"
            >
              <Search size={16} />
              Search
            </button>
          </div>
        </div>

        <div className="mt-4 flex items-center justify-between text-xs text-muted">
          <span>Date: {searchedAt.toLocaleString()}</span>
          <span>Total Transaction : {rows.length}</span>
        </div>

        <div className="mt-3 overflow-x-auto rounded-xl border border-border">
          <table className="min-w-full border-collapse text-xs">
            <thead>
              <tr className="bg-surface text-[11px] uppercase tracking-wide text-muted">
                {columns.map((col) => (
                  <th key={col} className="whitespace-nowrap border-b border-border px-3 py-2 text-left font-semibold">
                    {col}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {rows.length === 0 ? (
                <tr>
                  <td colSpan={columns.length} className="px-3 py-4 text-center text-muted">
                    No Records Found
                  </td>
                </tr>
              ) : (
                rows.map((row) => (
                  <tr key={row.sno} className="bg-panel">
                    <td className="whitespace-nowrap px-3 py-2 text-heading/80">{row.sno}</td>
                    <td className="whitespace-nowrap px-3 py-2 text-heading/80">{row.destCountry}</td>
                    <td className="whitespace-nowrap px-3 py-2 text-heading/80">{row.district}</td>
                    <td className="whitespace-nowrap px-3 py-2 text-heading/80">{row.receivingBranch}</td>
                    <td className="whitespace-nowrap px-3 py-2 text-heading/80">{row.receiver}</td>
                    <td className="whitespace-nowrap px-3 py-2 text-heading/80">{row.date}</td>
                    <td className="whitespace-nowrap px-3 py-2 text-heading/80">{row.paymentType}</td>
                    <td className="whitespace-nowrap px-3 py-2 text-right text-heading/80">{row.payoutAmount}</td>
                    <td className="whitespace-nowrap px-3 py-2 text-heading/80">{row.generatedBy}</td>
                  </tr>
                ))
              )}
            </tbody>
            <tfoot>
              <tr className="bg-surface font-semibold text-heading">
                <td colSpan={columns.length - 2} className="px-3 py-2">
                  Sub-Total Amount :
                </td>
                <td className="px-3 py-2 text-right">{subTotal.toFixed(2)}</td>
                <td className="px-3 py-2" />
              </tr>
              <tr className="bg-surface font-semibold text-heading">
                <td colSpan={columns.length - 2} className="px-3 py-2">
                  All Total Amount :
                </td>
                <td className="px-3 py-2 text-right">{subTotal.toFixed(2)}</td>
                <td className="px-3 py-2" />
              </tr>
            </tfoot>
          </table>
        </div>
      </div>
    </div>
  );
}
