"use client";

import { useState } from "react";
import { Search } from "lucide-react";
import Button from "./Button";
import { unpaidTransactionRows } from "@/data/remittanceListsData";

const filterOptions = ["All", "Sri Lanka", "Philippines", "Nepal", "Republic of Korea"];

const columns = [
  "Sno",
  "Pinno",
  "Dest. Country",
  "Receiver",
  "Date",
  "Payout Partner",
  "Bank Name",
  "Branch Name",
  "Account No",
  "Collect Amount",
  "Payout Amount",
  "Generated By",
];

export default function UnpaidTransactionsPanel() {
  const [filter, setFilter] = useState(filterOptions[0]);
  const [search, setSearch] = useState("");
  const [rows, setRows] = useState(unpaidTransactionRows);

  function handleSearch() {
    setRows(
      unpaidTransactionRows.filter((row) => {
        const matchesFilter = filter === "All" || row.destCountry.toLowerCase().includes(filter.toLowerCase());
        const matchesSearch = search
          ? row.receiver.toLowerCase().includes(search.toLowerCase()) ||
            row.pinno.toLowerCase().includes(search.toLowerCase())
          : true;
        return matchesFilter && matchesSearch;
      })
    );
  }

  return (
    <div className="overflow-hidden rounded-2xl border border-border shadow-card">
      <div className="border-b border-border px-6 py-4">
        <h1 className="text-lg font-bold text-heading">Unpaid Transactions</h1>
      </div>

      <div className="bg-panel p-6 sm:p-8">
        <div className="flex flex-wrap items-center gap-3 rounded-xl border border-border bg-panel p-4">
          <select
            value={filter}
            onChange={(event) => setFilter(event.target.value)}
            className="rounded-lg border border-border bg-panel px-2 py-1.5 text-sm text-heading focus:border-brand-green focus:outline-none focus:ring-1 focus:ring-brand-green"
          >
            {filterOptions.map((option) => (
              <option key={option} value={option}>
                {option}
              </option>
            ))}
          </select>
          <input
            value={search}
            onChange={(event) => setSearch(event.target.value)}
            placeholder="Search PIN No. or Receiver"
            className="min-w-[220px] flex-1 rounded-lg border border-border bg-panel px-3 py-1.5 text-sm text-heading focus:border-brand-green focus:outline-none focus:ring-1 focus:ring-brand-green"
          />
          <Button size="md" onClick={handleSearch} icon={<Search size={14} />}>
            Search
          </Button>
        </div>

        <div className="mt-4 overflow-x-auto rounded-xl border border-border">
          <table className="min-w-full border-collapse text-xs">
            <thead>
              <tr className="bg-brand-blue-light text-[11px] uppercase tracking-wide text-heading/70">
                {columns.map((col) => (
                  <th key={col} className="whitespace-nowrap border-b border-border px-3 py-2 text-left font-semibold">
                    {col}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody>
              {rows.length === 0 ? (
                <tr>
                  <td colSpan={columns.length} className="px-3 py-4 text-center text-muted">
                    No Records Found
                  </td>
                </tr>
              ) : (
                rows.map((row, index) => (
                  <tr key={row.pinno} className={index % 2 === 0 ? "bg-panel" : "bg-brand-green-light/30"}>
                    <td className="whitespace-nowrap px-3 py-2 text-heading/80">{row.sno}</td>
                    <td className="whitespace-nowrap px-3 py-2 font-medium text-brand-blue">{row.pinno}</td>
                    <td className="whitespace-nowrap px-3 py-2 text-heading/80">{row.destCountry}</td>
                    <td className="whitespace-nowrap px-3 py-2 font-medium text-brand-blue">{row.receiver}</td>
                    <td className="whitespace-nowrap px-3 py-2 text-heading/80">{row.date}</td>
                    <td className="whitespace-nowrap px-3 py-2 text-heading/80">{row.payoutPartner}</td>
                    <td className="whitespace-nowrap px-3 py-2 text-heading/80">{row.bankName}</td>
                    <td className="whitespace-nowrap px-3 py-2 text-heading/80">{row.branchName}</td>
                    <td className="whitespace-nowrap px-3 py-2 text-heading/80">{row.accountNo}</td>
                    <td className="whitespace-nowrap px-3 py-2 text-right text-heading/80">{row.collectAmount}</td>
                    <td className="whitespace-nowrap px-3 py-2 text-right text-heading/80">{row.payoutAmount}</td>
                    <td className="whitespace-nowrap px-3 py-2 text-heading/80">{row.generatedBy}</td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>

        <div className="mt-2 text-right text-xs font-semibold text-heading/70">
          Total Transaction : {rows.length}
        </div>
      </div>
    </div>
  );
}
